export const SMALL_DEVICES_BREAK_POINT = 576;
export const MEDIUM_DEVICES_BREAK_POINT = 768;
export const LARGE_DEVICES_BREAK_POINT = 992;
export const EXTRA_LARGE_DEVICES_BREAK_POINT = 1200;
export const EXTRA_EXTRA_LARGE_DEVICE_BREAK_POINTS = 1536;

export const MAX_WIDTH_PADDING = 15;
