export const SMALL_DEVICES_BREAK_POINT = 576
export const MEDIUM_DEVICES_BREAK_POINT = 768
export const LARGE_DEVICES_BREAK_POINT = 992
export const EXTRA_LARGE_DEVICES_BREAK_POINT = 1200
export const EXTRA_EXTRA_LARGE_DEVICE_BREAK_POINTS = 1536

export const SMALL_DEVICES_MAX_WIDTH = 540
export const MEDIUM_DEVICES_MAX_WIDTH = 720
export const LARGE_DEVICES_MAX_WIDTH = 960
export const EXTRA_LARGE_DEVICES_MAX_WIDTH = 1140

export const MAIN_THEME = {
  breakPoints: {
    sm: SMALL_DEVICES_BREAK_POINT,
    md: MEDIUM_DEVICES_BREAK_POINT,
    lg: LARGE_DEVICES_BREAK_POINT,
    xl: EXTRA_LARGE_DEVICES_BREAK_POINT,
    xxl: EXTRA_EXTRA_LARGE_DEVICE_BREAK_POINTS,
  },
}

export const MAX_WIDTH_PADDING = 15
